### ISSUE TITLE
[to do] 请求在英文模式下，支持英文单词输入

### ISSUE THREAD

**Issue by xqhjay** [amzxyz/rime_wanxiang#1]
即在ascii_mode 为英文模式时，输入英文不直接上屏，而是会作为输入码，对接英文单词翻译器

**Comment by amzxyz** [comment]
> 即在ascii_mode 为英文模式时，输入英文不直接上屏，而是会作为输入码，对接英文单词翻译器

目前已经支持中英混输了，在我这够用，如果实在需要完善的英文输入体验需要单独做英文方案通过快捷键在方案之间切换
