### ISSUE TITLE
使用18键（小鹤双拼）输入法，怎么能避免单键候选词全是英文

### ISSUE THREAD

**Issue by kmyqchy** [amzxyz/rime_wanxiang#10]
试了注释  - ascii_composer，修改
reduce_english_filter:
  mode: all  # all | custom | none
  idx: 2  
好像都不行，能不能首选是中文，设置哪里可以降低这个权重或者彻底关闭也可以。
<img width="884" alt="image" src="https://github.com/user-attachments/assets/45ad266b-a138-4809-81da-9d72b27e6bc8" />
  如图我期望出来的是【我】

**Comment by amzxyz** [comment]
dependencies下的英语模块注释掉

**Comment by amzxyz** [comment]
更想说的是是不是配置改错了导致中文输入没生效

**Comment by kmyqchy** [comment]
感谢
----
# Rime schema
# encoding: utf-8
# 方案说明
########################万象拼音无辅助码版本，支持同文8、14、18键 ###########################
set_shuru_schema:         #配置此项就是选择什么输入法,同时拆分反查和中英文混输也将匹配该输入方案
  __include: 小鹤  #可选解码规则有   全拼, 自然码, 自然龙, 小鹤,  紫光, 搜狗, 微软, ABC  选择一个填入
set_gongjian_mohu:    #可选的值有：18键, 14键, 9键, 26键  ，PC请选26键
  __include: 18键
pro_comment_format:           # 超级注释模块
  candidate_length: 1         # 候选词注释提醒的生效长度，0为关闭  但同时清空其它，应当使用开关或者快捷键来处理    
  corrector_type: "{comment}"  #错音错词提示显示类型，比如"({comment})" 
########################以下是方案配置######################################################
应该没有吧，这个注释之后单键的候选词变成了中英混词

**Comment by kmyqchy** [comment]
换成最新版release 可以了

**Comment by kmyqchy** [comment]
```---
name: wanxiang
version: "2024.12.20"
sort: by_weight  #字典初始排序，可選original或by_weight
use_preset_vocabulary: false
import_tables:
  - cn_dicts/chars            #字表，包含了所有带拼音的汉字
  - cn_dicts/base            #基础词库，2-3字词汇
  - cn_dicts/correlation     #关联词库，4字词汇，多为不同词频的2字语句连接起来起到合理组句的能力
  - cn_dicts/associational   #联想词库，5字以上词汇，多用于输入前半段第二候选可以出来整段
  - cn_dicts/corrections     #错音错字，支持错音和错字输入的兼容，同时供超级注释lua使用会在输入错误音节打出的时候给予提示
  - cn_dicts/compatible      #兼容词库，是基础词库的扩充，收录了多场景多种读音的词组
  # - cn_dicts/customer        #搜狗自定义词库 ```
  我知道为啥了，这里我加了个词库就这样了
