### ISSUE TITLE
large.dict大字表部分字读音有误

### ISSUE THREAD

**Issue by eko5624** [amzxyz/rime_wanxiang#2]
比如`韫` 是多音字，读作 `yùn` `wēn`，字表中的2个读音都是 `yùn`。

**Comment by amzxyz** [comment]
> 比如`韫` 是多音字，读作 `yùn` `wēn`，字表中的2个读音都是 `yùn`。

收到，已经在修订4万字级别读音，包含cjk基于区到扩展g区所有有读音的字表，静待更新！

**Comment by eko5624** [comment]
`绿`读音也有误，如下：
```
绿	lù:	0
绿	lǜ	0
绿	lù̈	0
绿	lù	0
```

**Comment by amzxyz** [comment]
好的，最近在憋大招，还未完全完成，先释放出来直接下载可以体验，词组的读音放在最后解决，先炼制了全新词库和大模型
