### ISSUE TITLE
README.md中的末尾数字声调示例有误？

### ISSUE THREAD

**Issue by eko5624** [amzxyz/rime_wanxiang#4]
用末尾数字声调版打`虐待`时发现打不出来`nüe`。 `- xform/^(.*)ü(.*)$/$1v$2①/`是不是应该修改为`- xform/^(.*)ü(.*)$/$1v$2/`才是正确的？

**Comment by amzxyz** [comment]
不能叫有误，很多时候轻声归并到了1声，如你所说，他只是个例子，这要看你自己后面要怎么用，要用归并试得还是分离

**Comment by amzxyz** [comment]
nüè 的音调在e上面，可以改成üè 转 ve

**Comment by eko5624** [comment]
好的，多谢提示。

**Comment by eko5624** [comment]
加上这句后`- xform/\bn\b/en/   #解决𧗈字拼音n通过双拼en打出来`  `nüe`打不出来。我觉得这句应该修改为：
`- xform/^n$/en/   #解决𧗈字拼音n通过双拼en打出来`
